server:
  port: 8084

spring:
  application:
    name: core-service
  config:
    import: "optional:nacos:${spring.application.name}.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/cptracker
    username: ${POSTGRES_USER:cptracker}
    password: ${POSTGRES_PASSWORD:cptracker123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850}
        file-extension: yaml

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
